// src/companyNames.js

const companyNames = [
    "Walt Disney Co",
    "General Motors Co",
    "WW Grainger Inc",
    "Mohawk Industries Inc",
    "Live Nation Entertainment Inc",
    "Las Vegas Sands Corp",
    "Clorox Co",
    "ATA Creativity Global",
    "American Airlines Group Inc",
    "Atlantic American Corp",
    "Applied Optoelectronics Inc",
    "Aaon Inc",
    "Apple Inc",
    "Autoscope Technologies Corp",
    "Atlas Air Worldwide Holdings Inc",
    "Armada Acquisition Corp I",
    "Aadi Bioscience Inc",
    "Abeona Therapeutics Inc",
    "Airbnb Inc",
    "ARCA Biopharma Inc",
    "ABIOMED Inc",
    "Acumen Pharmaceuticals Inc",
    "Absci Corp",
    "Allegiance Bancshares Inc",
    "Arbutus Biopharma Corp",
    "ABVC Biopharma Inc",
    "ACADIA Pharmaceuticals Inc",
    "Acri Capital Acquisition Corp",
    "Accolade Inc",
    "Adicet Bio Inc",
    "Abcellera Biologics Inc",
    "Ameris Bancorp",
    "ACE Convergence Acquisition Corp",
    "Achilles Therapeutics PLC",
    "Acadia Healthcare Company Inc",
    "ACI Worldwide Inc",
    "Axcelis Technologies Inc",
    "AC Immune SA",
    "Achieve Life Sciences Inc",
    "ACM Research Inc",
    "Acorda Therapeutics Inc",
    "ACNB Corp",
    "Aclaris Therapeutics Inc",
    "AcelRx Pharmaceuticals Inc",
    "Enact Holdings Inc",
    "Acacia Research Corp",
    "ACV Auctions Inc",
    "Adagene Inc",
    "Acurx Pharmaceuticals Inc",
    "Adobe Inc",
    "Adaptimmune Therapeutics PLC",
    "ADMA Biologics Inc",
    "Advanced Emissions Solutions Inc",
    "Analog Devices Inc",
    "Adial Pharmaceuticals Inc",
    "Adamis Pharmaceuticals Corp",
    "Acer Therapeutics Inc",
    "Edoc Acquisition Corp",
    "Addus Homecare Corp",
    "Arch Capital Group Ltd",
    "Adaptive Biotechnologies Corp",
    "Autodesk Inc",
    "Automatic Data Processing Inc",
    "Aditxt Inc",
    "Advantage Solutions Inc",
    "Adverum Biotechnologies Inc",
    "Aehr Test Systems",
    "Antelope Enterprise Holdings Ltd",
    "Alset Ehome International Inc",
    "Advanced Energy Industries Inc",
    "American Electric Power Company Inc",
    "Aethlon Medical Inc",
    "Allied Esports Entertainment Inc",
    "AudioEye Inc",
    "Aerie Pharmaceuticals Inc",
    "ADDvantage Technologies Group Inc",
    "AF Acquisition Corp",
    "Affimed NV",
    "AFC Gamma Inc",
    "Affinity Bancshares Inc",
    "Affirm Holdings Inc",
    "Acutus Medical Inc",
    "Agenus Inc",
    "Afya Ltd",
    "AgroFresh Solutions Inc",
    "Agrify Corp",
    "AgileThought Inc",
    "AGM Group Holdings Inc",
    "Agios Pharmaceuticals Inc",
    "Aeglea Bio Therapeutics Inc",
    "AGNC Investment Corp",
    "AgriFORCE Growing Systems Ltd",
    "Agile Therapeutics Inc",
    "Agilysys Inc",
    "Applied Genetic Technologies Corp",
    "Adapthealth Corp",
    "Allied Healthcare Products Inc",
    "AIB Acquisition Corp",
    "ADTRAN Inc",
    "Advent Technologies Holdings Inc",
    "Aikido Pharma Inc",
    "Sports Ventures Acquisition Corp",
    "Arteris Inc",
    "Akero Therapeutics Inc",
    "Air T Inc",
    "Altra Industrial Motion Corp",
    "Akebia Therapeutics Inc",
    "Airgain Inc",
    "Airsculpt Technologies Inc",
    "Akamai Technologies Inc",
    "Akumin Inc",
    "Akouos Inc",
    "Akoustis Technologies Inc",
    "Akari Therapeutics PLC",
    "Albireo Pharma Inc",
    "Akoya Biosciences Inc",
    "Alico Inc",
    "Aldeyra Therapeutics Inc",
    "Alector Inc",
    "Allegro Microsystems Inc",
    "Alfi Inc",
    "Align Technology Inc",
    "Aligos Therapeutics Inc",
    "Alignment Healthcare LLC",
    "Alkermes Plc",
    "Alimera Sciences Inc",
    "Allegiant Travel Co",
    "Aesthetic Medical International Holdings Group Ltd",
    "Alkami Technology Inc",
    "Alnylam Pharmaceuticals Inc",
    "Allot Ltd",
    "Allogene Therapeutics Inc",
    "Applied Materials Inc",
    "Advanced Micro Devices Inc",
    "Activision Blizzard Inc",
    "Broadcom Inc",
    "ANSYS Inc",
    "Amazon.com Inc",
    "Senmiao Technology Ltd",
    "APA Corp (US)",
    "Biogen Inc",
    "Booking Holdings Inc",
    "Cadence Design Systems Inc",
    "CDW Corp",
    "CH Robinson Worldwide Inc",
    "Cincinnati Financial Corp",
    "Charter Communications Inc",
    "Comcast Corp",
    "Copart Inc",
    "Costco Wholesale Corp",
    "CSX Corp",
    "Cognizant Technology Solutions Corp",
    "CME Group Inc",
    "Cisco Systems Inc",
    "Cintas Corp",
    "Citrix Systems Inc",
    "Caesars Entertainment Inc",
    "DISH Network Corp",
    "Dollar Tree Inc",
    "Dexcom Inc",
    "Electronic Arts Inc",
    "Alliant Energy Corp",
    "Diamondback Energy Inc",
    "eBay Inc",
    "LKQ Corp",
    "Alphabet Inc",
    "Marriott International Inc",
    "Microchip Technology Inc",
    "Lam Research Corp",
    "Mondelez International Inc",
    "Meta Platforms Inc",
    "Marketaxess Holdings Inc",
    "Monster Beverage Corp",
    "Moderna Inc",
    "Match Group Inc",
    "Monolithic Power Systems Inc",
    "Microsoft Corp",
    "Micron Technology Inc",
    "Nasdaq Inc",
    "NortonLifeLock Inc",
    "Northern Trust Corp",
    "Newell Brands Inc",
    "NVIDIA Corp",
    "Allakos Inc",
    "News Corp",
    "Old Dominion Freight Line Inc",
    "Paccar Inc",
    "NXP Semiconductors NV",
    "O'Reilly Automotive Inc",
    "Paychex Inc",
    "Principal Financial Group Inc",
    "Ross Stores Inc",
    "SBA Communications Corp",
    "Qualcomm Inc",
    "Pool Corp",
    "PepsiCo Inc",
    "Starbucks Corp",
    "Regency Centers Corp",
    "Qorvo Inc",
    "PTC Inc",
    "PENN Entertainment Inc",
    "PayPal Holdings Inc",
    "Regeneron Pharmaceuticals Inc",
    "Amgen Inc",
    "Synopsys Inc",
    "Seagate Technology Holdings PLC",
    "Bio-Techne Corp",
    "Teradyne Inc",
    "Skyworks Solutions Inc",
    "Trimble Inc",
    "T Rowe Price Group Inc",
    "Take-Two Interactive Software Inc",
    "Tesla Inc",
    "Tractor Supply Co",
    "Texas Instruments Inc",
    "T-Mobile US Inc",
    "United Airlines Holdings Inc",
    "Verisk Analytics Inc",
    "Ulta Beauty Inc",
    "Vertex Pharmaceuticals Inc",
    "Viatris Inc",
    "Verisign Inc",
    "Walgreens Boots Alliance Inc",
    "NetApp Inc",
    "Xcel Energy Inc",
    "DENTSPLY SIRONA Inc",
    "Zebra Technologies Corp",
    "Advance Auto Parts Inc",
    "Zions Bancorporation NA",
    "Wynn Resorts Ltd",
    "Agilent Technologies Inc",
    "Abbvie Inc",
    "Amerisourcebergen Corp",
    "Archer-Daniels-Midland Co",
    "Abbott Laboratories",
    "Ameren Corp",
    "AES Corp",
    "Aflac Inc",
    "Accenture PLC",
    "Arthur J. Gallagher & Co.",
    "Assurant Inc",
    "Alaska Air Group Inc",
    "Albemarle Corp",
    "American International Group Inc",
    "Allstate Corp",
    "Allegion PLC",
    "Ameriprise Financial Inc",
    "AMETEK Inc",
    "American Tower Corp",
    "A O Smith Corp",
    "Air Products and Chemicals Inc",
    "Aon PLC",
    "Arista Networks Inc",
    "Amphenol Corp",
    "Atmos Energy Corp",
    "American Water Works Company Inc",
    "Alexandria Real Estate Equities Inc",
    "Aptiv PLC",
    "Avalonbay Communities Inc",
    "Avery Dennison Corp",
    "Boeing Co",
    "Bank of America Corp",
    "Baxter International Inc",
    "Bath & Body Works Inc",
    "Becton Dickinson and Co",
    "Bio Rad Laboratories Inc",
    "Best Buy Co Inc",
    "Bank of New York Mellon Corp",
    "American Express Co",
    "Broadridge Financial Solutions Inc",
    "Bristol-Myers Squibb Co",
    "Brown & Brown Inc",
    "Broadcom Inc",
    "Berkshire Hathaway Inc",
    "Caterpillar Inc",
    "Chubb Ltd",
    "C.H. Robinson Worldwide Inc",
    "Church & Dwight Co Inc",
    "Cigna Group",
    "Colgate-Palmolive Co",
    "Clean Harbors Inc",
    "Comerica Inc",
    "Corteva Inc",
    "ConocoPhillips",
    "Campbell Soup Co",
    "CVS Health Corp",
    "Chevron Corp",
    "Chevron Corporation",
    "D.R. Horton Inc",
    "Dover Corp",
    "Dow Inc",
    "Dominion Energy Inc",
    "Duke Energy Corp",
    "DuPont de Nemours Inc",
    "Duke Realty Corp",
    "Darden Restaurants Inc",
    "Expeditors International of Washington Inc",
    "Evergy Inc",
    "Edwards Lifesciences Corp",
    "Electronic Arts Inc",
    "Emerson Electric Co",
    "Equity Residential",
    "Enphase Energy Inc",
    "Entergy Corp",
    "Eaton Corp PLC",
    "Ecolab Inc",
    "Edison International",
    "Eastman Chemical Co",
    "Extra Space Storage Inc",
    "Ford Motor Co",
    "Freeport-McMoRan Inc",
    "FirstEnergy Corp",
    "Fifth Third Bancorp",
    "FMC Corp",
    "Fastenal Co",
    "First Republic Bank",
    "Federal Realty Investment Trust",
    "Garmin Ltd",
    "General Dynamics Corp",
    "General Electric Co",
    "General Mills Inc",
    "Goldman Sachs Group Inc",
    "Hartford Financial Services Group Inc",
    "Humana Inc",
    "Hess Corp",
    "Honeywell International Inc",
    "HP Inc",
    "Hewlett Packard Enterprise Co",
    "Huntington Ingalls Industries Inc",
    "Hologic Inc",
    "Home Depot Inc",
    "Interpublic Group of Companies Inc",
    "Intel Corp",
    "International Business Machines Corp",
    "Johnson & Johnson",
    "Johnson Controls International PLC",
    "JPMorgan Chase & Co",
    "Kellogg Co",
    "Keurig Dr Pepper Inc",
    "Kroger Co",
    "Kimco Realty Corp",
    "Kraft Heinz Co",
    "Lam Research Corp",
    "Liberty Media Corp",
    "Las Vegas Sands Corp",
    "Lamb Weston Holdings Inc",
    "Leidos Holdings Inc",
    "Linde PLC",
    "L3Harris Technologies Inc",
    "Loews Corp",
    "Lowe's Companies Inc",
    "MSCI Inc",
    "MarketAxess Holdings Inc",
    "Marriott International Inc",
    "Marsh & McLennan Companies Inc",
    "Masco Corp",
    "Mastercard Inc",
    "McDonald's Corp",
    "Mckesson Corp",
    "Medtronic PLC",
    "Merck & Co Inc",
    "Meta Platforms Inc",
    "Micron Technology Inc",
    "Microchip Technology Inc",
    "Mettler-Toledo International Inc",
    "Moderna Inc",
    "Monolithic Power Systems Inc",
    "Mohawk Industries Inc",
    "NCR Corp",
    "NetApp Inc",
    "Netflix Inc",
    "NextEra Energy Inc",
    "Nordstrom Inc",
    "Norfolk Southern Corp",
    "Northern Trust Corp",
    "Northrop Grumman Corp",
    "Nucor Corp",
    "NVIDIA Corp",
    "Old Dominion Freight Line Inc",
    "ON Semiconductor Corp",
    "Otis Worldwide Corp",
    "PayPal Holdings Inc",
    "PPL Corp",
    "PepsiCo Inc",
    "Pfizer Inc",
    "Philip Morris International Inc",
    "Prologis Inc",
    "Prudential Financial Inc",
    "Qualcomm Inc",
    "Raytheon Technologies Corp",
    "Republic Services Inc",
    "Rockwell Automation Inc",
    "Rollins Inc",
    "Royal Caribbean Cruises Ltd",
    "RPM International Inc",
    "Salesforce Inc",
    "Snap-On Inc",
    "Southern Co",
    "Starbucks Corp",
    "State Street Corp",
    "Stryker Corp",
    "SunTrust Banks Inc",
    "Synchrony Financial",
    "Sysco Corp",
    "TE Connectivity Ltd",
    "T Rowe Price Group Inc",
    "T-Mobile US Inc",
    "Target Corp",
    "Texas Instruments Inc",
    "The Travelers Companies Inc",
    "Truist Financial Corp",
    "Twitter Inc",
    "United Parcel Service Inc",
    "U.S. Bancorp",
    "Valero Energy Corp",
    "Visa Inc",
    "Vulcan Materials Co",
    "Walmart Inc",
    "Walgreens Boots Alliance Inc",
    "Walt Disney Co",
    "Waste Management Inc",
    "Western Digital Corp",
    "Whirlpool Corp",
    "Willis Towers Watson PLC",
    "Zebra Technologies Corp"
  ];
  
  export default companyNames;
  